/**
 * Compact liquid US universe (~35 symbols) for screening.
 * Market data: Yahoo v8 chart (same host as portfolio quotes). Fundamentals: SEC.
 * Sectors are static labels for the screener filter (v8 meta sector is unreliable).
 */
export const SCREENER_UNIVERSE: readonly string[] = [
  "AAPL",
  "MSFT",
  "GOOGL",
  "AMZN",
  "META",
  "NVDA",
  "INTC",
  "AMD",
  "AVGO",
  "JPM",
  "BAC",
  "GS",
  "XOM",
  "CVX",
  "COP",
  "SLB",
  "OXY",
  "RIG",
  "JNJ",
  "UNH",
  "MRK",
  "PFE",
  "ABBV",
  "WMT",
  "COST",
  "HD",
  "DIS",
  "KO",
  "PEP",
  "CAT",
  "BA",
  "UPS",
  "NEE",
  "IBM",
  "ABAT",
] as const;

/** GICS-style sector labels for the screener universe (no live sector API). */
export const UNIVERSE_SECTOR_BY_TICKER: Readonly<Record<string, string>> = {
  AAPL: "Technology",
  MSFT: "Technology",
  GOOGL: "Technology",
  AMZN: "Consumer Cyclical",
  META: "Technology",
  NVDA: "Technology",
  INTC: "Technology",
  AMD: "Technology",
  AVGO: "Technology",
  JPM: "Financial Services",
  BAC: "Financial Services",
  GS: "Financial Services",
  XOM: "Energy",
  CVX: "Energy",
  COP: "Energy",
  SLB: "Energy",
  OXY: "Energy",
  RIG: "Energy",
  JNJ: "Healthcare",
  UNH: "Healthcare",
  MRK: "Healthcare",
  PFE: "Healthcare",
  ABBV: "Healthcare",
  WMT: "Consumer Defensive",
  COST: "Consumer Defensive",
  HD: "Consumer Cyclical",
  DIS: "Communication Services",
  KO: "Consumer Defensive",
  PEP: "Consumer Defensive",
  CAT: "Industrials",
  BA: "Industrials",
  UPS: "Industrials",
  NEE: "Utilities",
  IBM: "Technology",
  ABAT: "Technology",
};
